# Generated by Django 3.1.7 on 2021-05-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='object',
        ),
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
