# Generated by Django 3.2.3 on 2021-06-04 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listings',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listings',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 16, 47, 24, 3825)),
        ),
    ]
