# Generated by Django 3.2.3 on 2021-06-05 01:26

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210604_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AddField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(related_name='my_watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 9, 26, 51, 262119)),
        ),
    ]
