# Generated by Django 3.2.3 on 2021-06-05 01:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210605_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 9, 56, 12, 550986)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
