# Generated by Django 3.2.3 on 2021-06-05 10:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210605_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 18, 27, 40, 711171)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='my_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
